version: "3.9"

services:
  catalog_api:
    build: ./catalog_api
    container_name: catalog_api
    ports:
      - 8080:8080
    volumes:
      - ./catalog_api:/app
    command: "sh entrypoint.sh"
    depends_on:
      - catalog_db
      - rabbitmq


  catalog_db:
    image: mysql:latest
    container_name: catalog_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./catalog_api/.docker/mysql:/var/lib/mysql
      - ./catalog_api/./db.sql:/docker-entrypoint-initdb.d/db.sql


  order_api:
    build: ./order_api
    container_name: order_api
    ports:
      - 3000:3000
    volumes:
      - ./order_api:/app
    command: sh entrypoint.sh
    depends_on:
      - order_db
      - rabbitmq


  order_db:
    image: mysql:8.0.30
    container_name: order_db
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=order_api


  payment_api:
    build: ./payment_api
    container_name: payment_api
    volumes:
      - ./payment_api:/app
    command: sh entrypoint.sh
    depends_on:
      - rabbitmq


  store_client:
    build: ./store_client
    container_name: store_client
    ports:
      - 3001:3001
    volumes:
      - ./store_client:/app
    command: sh entrypoint.sh
    depends_on:
      - catalog_api
      - order_api


  image_server:
    build: ./store_client
    container_name: image_server
    ports:
      - 9000:9000
    volumes:
      - ./store_client:/app
    command: npx serve -l 9000 images

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

